name: Deploy to Hostinger (Vite + FTP)

on:
  push:
    branches: [main] 
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Build (Vite)
        run: npm run build

      # Dijagnostika
      - name: List dist
        run: |
          echo "root:"
          ls -lah
          echo "dist:"
          ls -lah dist || echo "dist missing!"

      # Kopiranje PHP fajlova
      - name: Copy backend files
        run: |
          cp upload.php dist/
          cp edit.php dist/
          cp delete.php dist/
          mkdir -p dist/uploads
          cp uploads/images.json dist/uploads/images.json || echo "[]" > dist/uploads/images.json

      # Generiši secret.key sa lozinkom
      - name: Create password file
        run: echo "${{ secrets.GALLERY_PASSWORD }}" > dist/secret.key

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          protocol: ftps
          local-dir: dist/
          server-dir: /
          log-level: verbose
          timeout: 180000
          state-name: .ftp-deploy-sync.json
